on: [push]

name: Build_And_Deploy_To_Azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: contoso.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t applebot.azurecr.io/applebot:${{ github.sha }}
        docker push applebot.azurecr.io/applebot:${{ github.sha }}
        
    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'applebot'
        images: 'applebot.azurecr.io/applebot:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
